### PR TITLE
seems like there was a change in the hateoas handling for local urls

### PR DESCRIPTION
**Pull request by lsmith77**
@willdurand

### CODE REVIEW

**Comment by gimler** [comment]
i test it locally it works as accepted. Don't know why it fails on travis?

**Comment by lsmith77** [comment]
did you really ensure you had composer properly updated?

**Comment by gimler** [comment]
yes i remove the vendor folder and rerun `composer install --prefer-source`

**Comment by willdurand** [comment]
Weird

**Comment by gimler** [comment]
i get a 500 for the first test. i cat the log in a seperate branch  and i think the problem is
https://travis-ci.org/gimler/symfony-rest-edition/jobs/17648120

```
[2014-01-26 15:23:02] request.CRITICAL: Uncaught PHP Exception PHPUnit_Framework_Error_Notice: 
"Declaration of Hautelook\TemplatedUriRouter\Routing\Generator\Rfc6570Generator::doGenerate() should be 
compatible with Symfony\Component\Routing\Generator\UrlGenerator::doGenerate($variables, $defaults, 
$requirements, $tokens, $parameters, $name, $referenceType, $hostTokens, array $requiredSchemes = Array)" 
at /home/travis/build/gimler/symfony-rest-edition/vendor/hautelook/templated-uri-router/Hautelook
/TemplatedUriRouter/Routing/Generator/Rfc6570Generator.php line 29 {"exception":"[object] 
(PHPUnit_Framework_Error_Notice: Declaration of Hautelook\\TemplatedUriRouter\\Routing\\Generator
\\Rfc6570Generator::doGenerate() should be compatible with Symfony\\Component\\Routing\\Generator
\\UrlGenerator::doGenerate($variables, $defaults, $requirements, $tokens, $parameters, $name, $referenceType, 
$hostTokens, array $requiredSchemes = Array) at /home/travis/build/gimler/symfony-rest-edition/vendor/hautelook
/templated-uri-router/Hautelook/TemplatedUriRouter/Routing/Generator/Rfc6570Generator.php:29)"} []
```

**Comment by lsmith77** [comment]
yup .. that is why I referenced https://github.com/hautelook/TemplatedUriBundle/pull/12 in the description of this PR

**Comment by willdurand** [comment]
See https://github.com/hautelook/TemplatedUriRouter/pull/7

**Comment by lsmith77** [comment]
yeah .. i suspected as much .. which is why in my PR I said potentially the issue is fixed already and all that is missing is a new tag

**Comment by gimler** [comment]
ahh ok my error level was not correct now i get the error also locally ;)

**Comment by lsmith77** [comment]
@willdurand now I am totally confused .. locally these changes fix the issue .. but they seem to not be required on travis.

**Comment by willdurand** [comment]
Well, I don't remember any changes regarding absoluteness of URIs.

**Comment by lsmith77** [comment]
can anyone reproduce the issue I am having locally?

**Comment by willdurand** [comment]
let me try.

**Comment by lsmith77** [comment]
nevermind .. i killed my vendors and now it works without these changes

**Pull request closed without merging**
